# Generated by Django 3.1.4 on 2020-12-20 11:07
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def add_debug_user(apps, schema_editor):
    """Создание тестового юзера для отладки."""
    if not settings.DEBUG:
        return

    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    User.objects.create(
        email="migrated@mail.com",
        password=make_password("5130"),
        username="kir",
        is_active=True,
        is_superuser=True,
        is_staff=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                ("user_name", models.TextField(null=True)),
                ("first_name", models.TextField(null=True)),
                ("add_date", models.DateTimeField(auto_now_add=True)),
                ("authorize", models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(add_debug_user),
    ]
