# Generated by Django 3.1.4 on 2020-12-27 12:20
from django.db import migrations, models


def add_main_static(apps, schema_editor) -> None:
    """Добавляет статику."""
    Static = apps.get_model("main.Static")
    Static.objects.create(
        slug="main",
        link="https://occ-0-2794-2219.1.nflxso.net/dnm/api/v6/LmEnxtiAuzezXBjYXPuDgfZ4zZQ/AAAABSPrjQDeZC5a1YVfbODFnaUQ8sejisIEI62mvKcW-dJCV5IuoFDBgDa8MWFM5ZI5Gyc0HDdYUeaDzFF-cySZ64SfOwWptrY8c3EI.png?r=df2",
    )


class Migration(migrations.Migration):
    """Миграция, добавляющая таблички жанров и статики."""

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Static",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("description", models.CharField(max_length=128)),
                ("slug", models.CharField(max_length=10, unique=True)),
                ("add_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(add_main_static),
    ]
