# Generated by Django 3.1.4 on 2020-12-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_static'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField(null=True, unique=True)),
                ('title_eng', models.TextField(unique=True)),
                ('poster', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='main.Genre')),
            ],
            options={
                'verbose_name': 'Сериалы',
                'verbose_name_plural': 'Сериалы',
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.TextField()),
                ('message_id', models.IntegerField(unique=True)),
                ('episode', models.IntegerField()),
                ('season', models.IntegerField()),
                ('lang', models.CharField(choices=[('SUB', 'sub'), ('RUS', 'russian'), ('ENG', 'english')], default='RUS', max_length=3)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.series')),
            ],
            options={
                'verbose_name': 'Эпизоды',
                'verbose_name_plural': 'Эпизоды',
                'db_table': 'episodes',
                'unique_together': {('series', 'episode', 'season', 'lang')},
            },
        ),
    ]
